export enum PageEndPoints {
  HOME = "/",
  MYPAGE = "/mypage",
  MYPOST = "/mypage/myPost",
  MYLIKED = "/mypage/myLiked",
  COMMUNITY = "/community",
  QNA = "/community/qna",
  REVIEW = "/community/review",
  CHALLENGE_MAIN = "/challenge",
  CHALLENGE_VS = "/challenge/vs",
  CHALLENGE_SOLO = "/challenge/solo",
  CHALLENGE_RECRUIT = "/challenge/recruit",
  LOGIN = "/login",
  JOIN = "/join",
  SEARCH = "/search",
}
