export enum PageEndPoints {
  HOME = "/",
  FIELD_VS = "/field/:id",
  MYPAGE = "/mypage",
  PROFILE = "/mypage/profile",
  MYPOST = "/mypage/myPost",
  MYPOST_EDIT = "/mypage/myPost/edit/:id",
  MYLIKED = "/mypage/myLiked",
  MYSETTINGS = "/mypage/settings",
  COMMUNITY = "/community",
  REVIEW_WRITE = "/community/review/write",
  QNA = "/community/qna",
  QNA_WRITE = "/community/qna/write",
  REVIEW = "/community/review",
  CHALLENGE_MAIN = "/challenge",
  CHALLENGE_CREATE = "/challenge/create",
  CHALLENGE_EDIT = "/challenge/edit/:id",
  CHALLENGE_VS = "/challenge/vs",
  CHALLENGE_VS_DETAIL = "/challenge/vs/detail/:id",
  CHALLENGE_VS_INVITE = "/challenge/vs/invite",
  CHALLENGE_SOLO = "/challenge/solo",
  CHALLENGE_SOLO_DETAIL = "/challenge/solo/detail/:id",
  CHALLENGE_RECRUIT = "/challenge/recruit",
  CHALLENGE_RECRUIT_WRITE = "/challenge/recruit/write",
  LOGIN = "/login",
  JOIN = "/join",
  SEARCH = "/search",
}

export enum ApiEndpoints {
  LOGIN = "/auth/login",
  JOIN = "/auth/register",
  EXIST_ID = "/auth/id-exist",
  PHOTO = "/files/images/:id",
}