import { ApiEndpoints } from "@/constants/endpoints";

enum Method {
    GET = "get",
    POST = "post",
    PUT = "put",
    PATCH = "patch",
    DELETE = "delete",
}

export const secureRoutes = [
    { method: Method.GET, url: ApiEndpoints.PHOTO },
    { method: Method.POST, url: ApiEndpoints.CHALLENGE },
    { method: Method.GET, url: ApiEndpoints.CHALLENGE_ALL },
    { method: Method.GET, url: ApiEndpoints.MY_PROFILE },
    { method: Method.GET, url: ApiEndpoints.CHALLENGE_SOLO },
    { method: Method.GET, url: ApiEndpoints.CHALLENGE_DETAIL_WEEKS },
    { method: Method.GET, url: ApiEndpoints.CHALLENGE_VS_DETAIL },
    { method: Method.GET, url: ApiEndpoints.CHALLENGE_DETAIL_WEEKS_COMMENTS },
    { method: Method.GET, url: ApiEndpoints.CHALLENGE_SOLO_DETAIL },
    { method: Method.POST, url: ApiEndpoints.CHALLENGE_DETAIL_WEEKS_COMMENTS },
    { method: Method.POST, url: ApiEndpoints.CHALLENGE_DETAIL_WEEKS_PROOF },
    { method: Method.POST, url: ApiEndpoints.CHALLENGE_LIKE },
    { method: Method.POST, url: ApiEndpoints.VS_RECRUIT },
    { method: Method.POST, url: ApiEndpoints.VS_REQUEST },
    { method: Method.GET, url: ApiEndpoints.VS_REQUEST_LIST },
    { method: Method.GET, url: ApiEndpoints.MY_CHALLENGE_LIST },
    { method: Method.GET, url: ApiEndpoints.POST_COMMENTS },
    { method: Method.POST, url: ApiEndpoints.POST_COMMENTS },
    { method: Method.POST, url: ApiEndpoints.POST_LIKE },
    { method: Method.POST, url: ApiEndpoints.LOGOUT },
    { method: Method.POST, url: ApiEndpoints.REVIEW },
    { method: Method.POST, url: ApiEndpoints.QNA },
    { method: Method.GET, url: ApiEndpoints.QNA_DETAIL },
    { method: Method.GET, url: ApiEndpoints.USER_CHALLENGE_RECORD },
    { method: Method.GET, url: ApiEndpoints.REVIEW_DETAIL },
    { method: Method.GET, url: ApiEndpoints.USER_MY_LEVEL },
    { method: Method.GET, url: ApiEndpoints.USER_MY_PROFILE },
    { method: Method.GET, url: ApiEndpoints.USER_MY_POST },
    { method: Method.GET, url: ApiEndpoints.USER_MY_LIKED },
];